server {
    listen 80;
    server_name inspector.quandh.online;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name inspector.quandh.online;
    root /www/wwwroot/inspector.quandh.online;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/inspector.quandh.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/inspector.quandh.online/privkey.pem;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        alias /www/wwwroot/inspector.quandh.online/api/public/;
        try_files $uri $uri/ @laravel;

        location ~ \.php$ {
            fastcgi_pass  unix:/tmp/php-cgi-83.sock;
            fastcgi_index index.php;
            include fastcgi.conf;
            fastcgi_param PHP_VALUE "open_basedir=/www/wwwroot/inspector.quandh.online/:/tmp/:/proc/";
            fastcgi_param SCRIPT_FILENAME $request_filename;
        }
    }

    location @laravel {
        rewrite /api/(.*)$ /api/index.php?/$1 last;
    }

    location /storage/ {
        alias /www/wwwroot/inspector.quandh.online/api/storage/app/public/;
    }
}
